### ISSUE TITLE
Interação para ativação do usuário 

### ISSUE THREAD

**Issue by Bumbleblo** [Alohomora-team/2019.2-AlohomoraBot#14]
**Descrição da funcionalidade**

Nesse momento não existe um mecanismo que alerte o administrador do sistema sobre novos usuários e requisite ativação do usuário no sistema. O propósito desta issue é criar a interação que permita o administrador ver todos os usuários que não estão ativados no sistema e consiga ativa-los ou não.

**Tarefas necessárias**

- [ ] Adicionar mudanças no CHANGELOG
- [ ] Realizar testes da funcionalidade
- [ ] Interação que busca na API todos os usuários não ativados e ative os usuários usando a mutation.
- [ ] Verificar se o usuário que esta acessando esta funcionalidade é realmente um administrador do sistema

**Comment by baraky** [comment]
Dando início na resolução da issue. Estavamos esperando que o PR #26 - Banco de dados do Bot fosse aprovado.
