### ISSUE TITLE
Refatoração do código do bot

### ISSUE THREAD

**Issue by Bumbleblo** [Alohomora-team/2019.2-AlohomoraBot#23]
**Descreva a solução que gostaria**

Esta issue tem o propósito de melhorar o código do bot.

**Funcionalidades requeridas**

- [ ] Alterar variáveis para nomes mais significativos
- [ ] Refatorar possíveis erros de duplicação
- [ ] Organizar nova estrutura de arquivos
- [ ] Rodar testes e garantir que estão rodando

**Contexto Adicional**
Adicionem outros contextos e fotos das telas

**Comment by baraky** [comment]
Vamos iniciar a referatoração do código do bot, estava em pendência o merge do banco de dados do bot para a resolução.

**Comment by baraky** [comment]
A issue está quase finalizada em termos de funcionalidades adicionadas, faltando "apenas" melhorar a qualidade do código.
