### ISSUE TITLE
Paralelizar estagios do CI no bot

### ISSUE THREAD

**Issue by sammyzord** [Alohomora-team/2019.2-AlohomoraBot#29]
**Descreva a solução que gostaria**
O lint está quebrando todas as outras fases do CI

**Funcionalidades requeridas**
Paralelizar os estagios de qualidade de código no CI

**Comment by Bumbleblo** [comment]
Como estamos indo nessa atividade ?

**Comment by sammyzord** [comment]
Eu tava vendo aqui e aparentemente o bot só tem dois estagios de CI, o lint e o deploy. Portanto nao faria sentida paralelizar esses dois. Porem, a estrutura já esta pronta para a adição de mais estagios se for necessário.
