### ISSUE TITLE
Atualizar interação de cadastro para salvar voz com o nome do usuário

### ISSUE THREAD

**Issue by Bumbleblo** [Alohomora-team/2019.2-AlohomoraBot#3]
**Descreva a solução que gostaria**

Atualizar interação do cadastro do usuário para que salve a voz com o nome do usuário.

**Funcionalidades requeridas**

- [x] Adicionar essa interação
- [ ] Adicionar entradas no CHANGELOG
- [ ] testes

**Comment by VictorJorgeFGA** [comment]
Pra eu poder começar a resolver essa issue é necessário que a issue #2 seja resolvida e o merge aconteça. Caso eu comece a fazer em cima do código atual, teremos que abrir uma nova issue pra dar "merge" nesse código com o do desacoplamento, que vão estar completamente diferentes em termos de estrutura.
