### ISSUE TITLE
Permitir autenticação por senha

### ISSUE THREAD

**Issue by Bumbleblo** [Alohomora-team/2019.2-AlohomoraBot#30]
**Descreva a solução que gostaria**

Criar opção na interação de autenticação que permita que o usuário possa se autenticar via senha se desejado.

**Funcionalidades requeridas**

- [x] Atualizar CHANGELOG com  as mudanças promovidas
- [x] Atualizar interação de autenticação com a subinteração de autenticação por senha

**Contexto Adicional**
Adicionem outros contextos e fotos das telas

**Comment by AlineLermen** [comment]
As mudanças para permitir a autenticação por senha foram adicionadas, só estão aguardando revisão.

Não sei se cabe comentar sobre isso aqui nessa issue, mas acredito que é interessante acrescentar o comando /autenticar, que havia sido retirado anteriormente. O @baraky também havia comentado sobre isso.
