### ISSUE TITLE
Criar interação de feedback do usuário 

### ISSUE THREAD

**Issue by Bumbleblo** [Alohomora-team/2019.2-AlohomoraBot#4]
**Descreva a solução que gostaria**

Adicionar interação de /feedback para que os usuários possam relatar problemas e expressa opiniões sobre o sistema.

**Funcionalidades requeridas**

- [ ] Adicionar interação de feedback
- [ ] Integrar com endpoint com a API
- [ ] Adicionar entradas no CHANGELOG
- [ ] Testes

**Comment by Bumbleblo** [comment]
Se demorar mais que 5 horas... já sabe né ?

**Comment by luis-furtado** [comment]
Estou tratando os conflitos para mandar o PR para análise (sem qualquer tipo de restrição para merge).
