### ISSUE TITLE
Melhoria dos testes para o bot

### ISSUE THREAD

**Issue by higton** [Alohomora-team/2019.2-AlohomoraBot#6]
Os testes precisam de melhorias para funcionar devidamente, pois não contabiliza os números de testes aceitos e os testes testam praticamente nada. O que foi feito foi apenas um teste de integração utilizando o tgintegration que manda uma mensagem para o bot e conta quantas mensagens foram mandadas.

**Funcionalidades requeridas**
Fazer com que os testes: 
- [ ] Não precisam do número do telefone
- [ ] Utilizem de apenas do pyrogram sem precisar do tgintegration, pois essa biblioteca que utiliza o pyrogram não é atualizada.
- [ ] Sejam melhorados para considerar cada cenário de aplicação.

E também:
- [ ] Criação de testes unitários do bot.(esses criados utilizam o de integração)

**Comment by Bumbleblo** [comment]
Essa issue não ta bem escrita.

1) Não fica claro  o porque os testes precisam ser melhoradors.
2) Não tem nenhuma referência ao pyrogram para que eu possa olhar diretamente o que a biblioteca faz e nenhuma evidência de como chegou a isso.
3) " Sejam melhorados para considerar cada caso" não é claro, cada caso do que ? Cada fluxo ? Cada linha ? Cada cenário da aplicação (um teste somente para testar um cadastro), fica muito vago o que é um "caso".

Outro ponto é que a issue ta sem milestone. Não foi planejada na semana porém tem estimativa.

**Comment by higton** [comment]
Obrigado pelas dicas, fiz algumas mudanças no texto agora deve estar tudo certo.

**Comment by Bumbleblo** [comment]
Realmente, agora ta show!

**Comment by higton** [comment]
Consegui realizar os testes unitários no bot, mas ainda falta conseguir realizar os testes com o arquivo de voz mockado. Como eu estou utilizando pytest, acho que já seria uma boa começar a utilizar o pytest em todo o projeto.

**Comment by Bumbleblo** [comment]
Decidimos que por causa das dificuldades de realizar o teste no bot estamos deixando essa issue de lado.
